<h1>Create</h1>
<?php
$this->form->setAttribute('action', $this->url('users', ['controller' => 'user', 'action' => 'read']));
$this->form->prepare();
echo $this->form()->openTag($form);
?>
<div>
	<?= $this->formHidden($form->get('id')); ?>
</div>
<div class="row">
	<div class="form-group col-lg-6">
		<label>Email address</label>
		<?= $this->formRow($form->get('emailAddress')); ?>
	</div>
	<div class="form-group col-lg-6">
		<label>Password</label>
		<?= $this->formRow($form->get('password')); ?>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-12">
		<?= $this->formSubmit($form->get('submit')); ?>
	</div>
</div>
<div>
	<?= $this->form()->closeTag(); ?>
</div>