<h1>User profile</h1>
<legend></legend>

<div class="row">
	<div class="col-lg-2">
		<h2>Info</h2>

		<div class="row">
			<div class="form-group col-lg-12">
				<label>Username</label>
				<input class="form-control input-sm" type="text" value="<?= $user->getUsername(); ?>" disabled/>
			</div>
		</div>
		<div class="row">
			<div class="form-group col-lg-12">
				<label>Role</label>
				<input class="form-control input-sm" type="text" value="<?= $user->getRole()->getName(); ?>" disabled/>
			</div>
		</div>
		<div class="row">
			<div class="form-group col-lg-12">
				<label>Email address</label>
				<div class="input-group">
					<input class="form-control input-sm" type="text" value="<?= $user->getEmailAddress(); ?>" disabled/>
					<div class="input-group-addon"><a class="glyphicon glyphicon-edit"></a></div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-10">
		<h2>
			Statistics
			<a href="/Statistic/add" class="pull-right">Add</a>
		</h2>
		<?php $statisticsGroupByMonths = $this->MyTable()->groupByMonths($user->getStatistics(), 'getDate'); ?>
		<?php foreach ($statisticsGroupByMonths as $stats) { ?>
			<div class="panel panel-default">
				<div class="panel-heading">
					<span class="bold"><?= $stats[0]->getDate()->format('F Y') ?></span>
				</div>
				<div class="panel-body">
					<table class="table table-hover table-condensed">
						<thead>
						<tr>
							<th>Date</th>
							<th>Wkg</th>
							<th>MM%</th>
							<th>MMkg</th>
							<th>BF%</th>
							<th>BFkg</th>
							<th>BW%</th>
						</tr>
						</thead>
						<tbody>
						<?php foreach ($stats as $statistic) { ?>
							<tr>
								<td><?= $statistic->getDate()->format('d'); ?></td>
								<td><?= number_format($statistic->getWeight(), 1); ?></td>
								<td><?= number_format($statistic->getMuscleMassPercentage(), 1); ?></td>
								<td><?= number_format($statistic->getMuscleMass(), 1); ?></td>
								<td><?= number_format($statistic->getBodyFatPercentage(), 1); ?></td>
								<td><?= number_format($statistic->getBodyFat(), 1); ?></td>
								<td><?= $statistic->getBodyWater(); ?></td>
<!--							<td>-->
<!--								<a href="/Statistic/delete/--><?php //echo $statistic->getId() ?><!--">Delete</a>-->
<!--							</td>-->
							</tr>
						<?php } ?>
						</tbody>
					</table>
				</div>
			</div>
		<?php } ?>
	</div>
</div>
<?php
//var_dump($user);
