<h1>Read</h1>
<table class="table table-condensed table-hover">
	<tr>
		<th>ID</th>
		<th>Created</th>
		<th>Email address</th>
		<th>Actions</th>
	</tr>
	<?php foreach ($users as $user) { ?>
		<tr>
			<td><a href="/users/user/get/<?= $user->getId(); ?>"><?= $user->getId(); ?></a></td>
			<td><?= $user->getCreated()->format('Y-m-d H:i:s'); ?></td>
			<td><?= $user->getEmailAddress(); ?></td>
			<td><a href="/Statistic/delete/<?= $user->getId(); ?>">Delete</a></td>
		</tr>
	<?php } ?>
</table>