<h1>Sign in</h1>
<?php
$this->form->setAttribute('action', '/users/user/login');
$this->form->prepare();
echo $this->form()->openTag($form);
?>
<div class="row">
	<div class="form-group col-lg-4">
		<?= $this->formRow($form->get('emailAddress')); ?>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-4">
		<?= $this->formRow($form->get('password')); ?>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-4">
		<label><?= $this->formRow($form->get('rememberMe')); ?> Remember me</label>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-4">
		<?= $this->formSubmit($form->get('submit')); ?>
	</div>
</div>
<div>
	<?= $this->form()->closeTag(); ?>
</div>