<table class="table">
	<tr>
		<th>ID</th>
		<th>Date</th>
		<th>User ID</th>
		<th>Weight</th>
		<th>Muscle Mass</th>
		<th>Body Fat</th>
		<th>Body Water</th>
		<th>Action</th>
	</tr>
	<?php foreach ($statistics as $statistic) { ?>
		<tr>
			<td><?= $statistic->id; ?></td>
			<td><?= $statistic->date; ?></td>
			<td><?= $statistic->userId; ?></td>
			<td><?= $statistic->weight; ?> kg</td>
			<td><?= $statistic->muscleMass; ?> %</td>
			<td><?= $statistic->bodyFat; ?> %</td>
			<td><?= $statistic->bodyWater; ?> %</td>
			<td>
				<a href="/Statistic/delete/<?= $statistic->id ?>">Delete</a>
			</td>
		</tr>
	<?php } ?>
</table>
