<table class="table">
	<tr>
		<th>ID</th>
		<th>Date</th>
		<th>User ID</th>
		<th>Weight</th>
		<th>Muscle Mass</th>
		<th>Body Fat</th>
		<th>Body Water</th>
		<th>Action</th>
	</tr>
	<?php foreach ($statistics as $statistic) { ?>
		<tr>
			<td><?= $statistic->getId(); ?></td>
			<td><?= $statistic->getDate()->format('Y-m-d H:i:s'); ?></td>
			<td><?= $statistic->getUser()->getId(); ?></td>
			<td><?= $statistic->getWeight(); ?> kg</td>
			<td><?= $statistic->getMuscleMass(); ?> %</td>
			<td><?= $statistic->getBodyFat(); ?> %</td>
			<td><?= $statistic->getBodyWater(); ?> %</td>
			<td>
				<a href="/Statistic/delete/<?= $statistic->getId(); ?>">Delete</a>
			</td>
		</tr>
	<?php } ?>
</table>
