<?= $this->doctype(); ?>

<html lang="en">
<head>
	<meta charset="utf-8">
	<?= $this->headTitle('MyWeight')->setAutoEscape(false) ?>
	<?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
	<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon','href' => $this->basePath() . '/img/favicon.ico'])
		->prependStylesheet($this->basePath() . '/css/style.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
	?>

	<!-- Scripts -->
	<?= $this->headScript()->prependFile($this->basePath() . '/js/bootstrap.min.js')->prependFile($this->basePath() . '/js/jquery.min.js')->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?= $this->url('home') ?>">
				<img src="<?= $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>
				&nbsp;MyWeight
			</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li>
					<a href="/users/user/index"><?= $this->translate('Users'); ?></a>
				</li>
				<li>
					<a href="<?= $this->url('statistic'); ?>"><?= $this->translate('Statistics'); ?></a>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<?php if ($user = $this->identity()) { ?>
					<li>
						<a href="/users/user/get/<?= $user->getId(); ?>"><?= $user->getUsername(); ?></a>
					</li>
				<?php } ?>
			</ul>
		</div>
	</div>
</nav>
<div class="container">
	<?= $this->content; ?>
	<hr>
	<footer>
		<p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies
			Ltd. <?= $this->translate('All rights reserved.') ?></p>
	</footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
